Modify redefinition of strdup
If the glibc version < 2.26.There are two
definitions of strdup in harness.h and string2.h.
This will cause a redefined error when compile.
Using macro #undef to undef the strdup defined
in string2.h:1291.